QT += core gui widgets

TEMPLATE = app

CONFIG += c++17
CONFIG -= qml_debug qtquickcompiler

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

TARGET = torque

SRC_PATH = $$PWD/src
INCLUDEPATH += $$PWD/src

SOURCES += \
    src/Database/Database.cpp \
    src/Database/DbAmbList.cpp \
    src/Database/DbDoctor.cpp \
    src/Database/DbInvoice.cpp \
    src/Database/DbListOpener.cpp \
    src/Database/DbNotes.cpp \
    src/Database/DbPatient.cpp \
    src/Database/DbPatientSummary.cpp \
    src/Database/DbPerio.cpp \
    src/Database/DbPractice.cpp \
    src/Database/DbProcedure.cpp \
    src/Database/sqLite/shell.c \
    src/Database/sqLite/sqlite3.c \
    src/JsonCpp/jsoncpp.cpp \
    src/Model/AmbListValidator.cpp \
    src/Model/CityCode.cpp \
    src/Model/Date.cpp \
    src/Model/Financial/BusinessOperation.cpp \
    src/Model/Financial/Invoice.cpp \
    src/Model/Financial/Issuer.cpp \
    src/Model/Financial/NzokInvoiceData.cpp \
    src/Model/Financial/Recipient.cpp \
    src/Model/InsuranceStatus.cpp \
    src/Model/KSMP.cpp \
    src/Model/Parser/Parser.cpp \
    src/Model/Patient.cpp \
    src/Model/PerioStatistic.cpp \
    src/Model/PerioToothData.cpp \
    src/Model/Procedure/CustomProcedures.cpp \
    src/Model/Procedure/MasterNZOK.cpp \
    src/Model/Procedure/PackageCounter.cpp \
    src/Model/Procedure/Procedure.cpp \
    src/Model/Procedure/ProcedureApplier.cpp \
    src/Model/Procedure/ProcedureParser.cpp \
    src/Model/Tooth/DiagnosisContainer.cpp \
    src/Model/Tooth/Tooth.cpp \
    src/Model/Tooth/ToothContainer.cpp \
    src/Model/Tooth/ToothController/BridgeController.cpp \
    src/Model/Tooth/ToothController/GeneralStatusControler.cpp \
    src/Model/Tooth/ToothController/SurfaceController.cpp \
    src/Model/Tooth/ToothParser.cpp \
    src/Model/Tooth/ToothUtils.cpp \
    src/Model/User/User.cpp \
    src/Model/Validator/BulstatValidator.cpp \
    src/Model/Validator/CommonValidators.cpp \
    src/Model/Validator/DateValidator.cpp \
    src/Model/Validator/LpkValidator.cpp \
    src/Model/Validator/NameValidator.cpp \
    src/Model/Validator/NzokContractValidator.cpp \
    src/Model/Validator/PatientValidators.cpp \
    src/Model/Validator/ProcedureDateValidator.cpp \
    src/Model/Validator/ProcedureValidators.cpp \
    src/Model/Validator/RziValidaor.cpp \
    src/Model/Validator/RziValidator.cpp \
    src/Model/XML/xml.cpp \
    src/Network/Base64Convert.cpp \
    src/Network/Network.cpp \
    src/Network/PISServ.cpp \
    src/Network/PKCS11.cpp \
    src/Network/ReplyHandlers/AbstractReplyHandler.cpp \
    src/Network/ReplyHandlers/DentalActivitiesHandler.cpp \
    src/Network/ReplyHandlers/FileSentHandler.cpp \
    src/Network/ReplyHandlers/HirbnoReplyHandler.cpp \
    src/Network/ReplyHandlers/MonthNotifDataHandler.cpp \
    src/Network/ReplyHandlers/NotifListHandler.cpp \
    src/Network/ReplyHandlers/NraReplyHandler.cpp \
    src/Network/XmlSigner.cpp \
    src/Presenter/AddPracticePresenter/AddPracticePresenter.cpp \
    src/Presenter/AllergiesDialog/AllergiesDialogPresenter.cpp \
    src/Presenter/AmbListPagePresenter.cpp \
    src/Presenter/DetailsPresenter/DetailedStatusPresenter.cpp \
    src/Presenter/DetailsPresenter/DetailsPresenter.cpp \
    src/Presenter/DoctorDialogPresenter/DoctorDialogPresenter.cpp \
    src/Presenter/FinancialPresenter/FinancialPresenter.cpp \
    src/Presenter/ListPresenter/CheckState.cpp \
    src/Presenter/ListPresenter/Editor.cpp \
    src/Presenter/ListPresenter/ListPresenter.cpp \
    src/Presenter/ListPresenter/ProcedurePresenter/ProcedurePresenter.cpp \
    src/Presenter/ListPresenter/StatusPresenter/CheckModelCreator.cpp \
    src/Presenter/ListPresenter/StatusPresenter/StatusControl.cpp \
    src/Presenter/ListPresenter/StatusPresenter/StatusPresenter.cpp \
    src/Presenter/ListPresenter/StatusPresenter/SurfacePanel/ButtonSurfaceMatrix.cpp \
    src/Presenter/ListPresenter/StatusPresenter/SurfacePanel/SurfacePanelPresenter.cpp \
    src/Presenter/ListPresenter/StatusPresenter/ToothHintCreator.cpp \
    src/Presenter/ListPresenter/SurfacePanel/ButtonSurfaceMatrix.cpp \
    src/Presenter/ListPresenter/SurfacePanel/SurfacePanelPresenter.cpp \
    src/Presenter/ListPresenter/ToothHintCreator.cpp \
    src/Presenter/ListSelector/ListSelectorPresenter.cpp \
    src/Presenter/LoginPresenter/LoginPresenter.cpp \
    src/Presenter/MainPresenter.cpp \
    src/Presenter/MonthNotifLoader.cpp \
    src/Presenter/PatientDialog/PatientDialogPresenter.cpp \
    src/Presenter/PatientSummaryPresenter/PatientSummaryPresenter.cpp \
    src/Presenter/PerioPresenter/PerioPresenter.cpp \
    src/Presenter/ProcedureDialog/ProcedureDialogPresenter.cpp \
    src/Presenter/ProcedureDialog/ProcedureEditorPresenter.cpp \
    src/Presenter/ProcedureDialog/SubPresenters/AbstractSubPresenter.cpp \
    src/Presenter/ProcedureDialog/SubPresenters/CrownPresenter.cpp \
    src/Presenter/ProcedureDialog/SubPresenters/EndoPresenter.cpp \
    src/Presenter/ProcedureDialog/SubPresenters/ExtractionPresenter.cpp \
    src/Presenter/ProcedureDialog/SubPresenters/FiberSplintPresenter.cpp \
    src/Presenter/ProcedureDialog/SubPresenters/GeneralMPresenter.cpp \
    src/Presenter/ProcedureDialog/SubPresenters/ImplantPresenter.cpp \
    src/Presenter/ProcedureDialog/SubPresenters/ObturationPresenter.cpp \
    src/Presenter/ProcedureDialog/SubPresenters/TeethMPresenter.cpp \
    src/Presenter/ProcedureDialog/SubPresenters/ToothProcedurePresenter.cpp \
    src/Presenter/ReportDialogPresenter/ReportDialogPresenter.cpp \
    src/Presenter/SettingsPresenter/PracticeDoctorSettingsPresenter.cpp \
    src/Presenter/SettingsPresenter/PracticeSettingsPresenter.cpp \
    src/Presenter/SettingsPresenter/PriceListSettingsPresenter.cpp \
    src/Presenter/SettingsPresenter/SettingsMainPresenter.cpp \
    src/Presenter/TabPresenter/ListInstance.cpp \
    src/Presenter/TabPresenter/TabPresenter.cpp \
    src/View/AddPracticeDialog/AddPracticeDialog.cpp \
    src/View/AllergiesDialog/AllergiesDialog.cpp \
    src/View/AmbListPage/AmbListPage.cpp \
    src/View/AmbListPage/TabView/TabBar.cpp \
    src/View/AmbListPage/TabView/TabView.cpp \
    src/View/AmbListPage/saveAsDialog/MnogoTypSpinBox.cpp \
    src/View/AmbListPage/saveAsDialog/SaveAsDialog.cpp \
    src/View/AmbListPage/saveDialog/SaveDialog.cpp \
    src/View/AmbListSelector/AmbListSelector.cpp \
    src/View/AmbListSelector/ListTable.cpp \
    src/View/AmbListSelector/ListsTableModel.cpp \
    src/View/AmbListSelector/Models/AmbListTableModel.cpp \
    src/View/AmbListSelector/Models/FinancialTableModel.cpp \
    src/View/AmbListSelector/Models/PatientTableModel.cpp \
    src/View/AmbListSelector/Models/PerioTableModel.cpp \
    src/View/DetailsView/DetailedStatus.cpp \
    src/View/DetailsView/DetailsView.cpp \
    src/View/DoctorSettingsDialog/DoctorSettingsDialog.cpp \
    src/View/ErrorMessage.cpp \
    src/View/FinancialView/BusinessOpAddDialog/BusinessOpAddDialog.cpp \
    src/View/FinancialView/BusinessOpEditDialog/BusinessOpEditDialog.cpp \
    src/View/FinancialView/BusinessOperationModel.cpp \
    src/View/FinancialView/FinancialTileButton.cpp \
    src/View/FinancialView/FinancialView.cpp \
    src/View/GlobalFunctions.cpp \
    src/View/KSMPDialog/KSMPDialog.cpp \
    src/View/ListView/ControlPanel/ControlPanel.cpp \
    src/View/ListView/ControlPanel/StatusButton.cpp \
    src/View/ListView/ListView.cpp \
    src/View/ListView/Procedures/ProcedureTable.cpp \
    src/View/ListView/Procedures/ProcedureTableModel.cpp \
    src/View/ListView/SurfacePanel/CPTooth.cpp \
    src/View/ListView/SurfacePanel/ControlPanelPolygon.cpp \
    src/View/ListView/SurfacePanel/SurfacePanel.cpp \
    src/View/ListView/TeethView/BridgeItem.cpp \
    src/View/ListView/TeethView/ContextMenu.cpp \
    src/View/ListView/TeethView/DsnToothGraphicsItem.cpp \
    src/View/ListView/TeethView/GraphicsView.cpp \
    src/View/ListView/TeethView/SelectionBox.cpp \
    src/View/ListView/TeethView/TeethViewScene.cpp \
    src/View/ListView/TeethView/ToothGraphicsItem.cpp \
    src/View/ListView/ToothPaintDevices/BridgePainter.cpp \
    src/View/ListView/ToothPaintDevices/CPToothPainter.cpp \
    src/View/ListView/ToothPaintDevices/SpriteRect.cpp \
    src/View/ListView/ToothPaintDevices/SpriteSheets.cpp \
    src/View/ListView/ToothPaintDevices/ToothPainter.cpp \
    src/View/ListView/ToothPaintDevices/ToothSprite.cpp \
    src/View/ListView/tilebutton.cpp \
    src/View/LoginView/LoginView.cpp \
    src/View/LoginView/PracticeListDialog.cpp \
    src/View/ModalDialogBuilder.cpp \
    src/View/MonthNotifDialog/MonthNotifDialog.cpp \
    src/View/MonthNotifDialog/MonthNotifTableModel.cpp \
    src/View/PISHistoryDialog/PISHistoryDialog.cpp \
    src/View/PatientDialog/PatientFormDialog.cpp \
    src/View/PatientSummaryView/PatientSummary.cpp \
    src/View/PatientSummaryView/TeethView/TeethBuccalScene.cpp \
    src/View/PatientSummaryView/TeethView/TeethLingualScene.cpp \
    src/View/PerioView/PerioGraphics/HexagonGraphicsItem.cpp \
    src/View/PerioView/PerioGraphics/PerioChartItem.cpp \
    src/View/PerioView/PerioGraphics/PerioGraphicsButton.cpp \
    src/View/PerioView/PerioGraphics/PerioScene.cpp \
    src/View/PerioView/PerioView.cpp \
    src/View/PerioView/StatisticTableModel.cpp \
    src/View/PerioView/Widgets/FurcationWidget.cpp \
    src/View/PerioView/Widgets/PerioButton.cpp \
    src/View/PerioView/Widgets/PerioSpinBox.cpp \
    src/View/PerioView/Widgets/PerioStateButton.cpp \
    src/View/PerioView/Widgets/PerioStatusView.cpp \
    src/View/PerioView/Widgets/PerioTable.cpp \
    src/View/PerioView/Widgets/ToothButton.cpp \
    src/View/PinPromptDialog/PinPromptDialog.cpp \
    src/View/Printer/Printer.cpp \
    src/View/Printer/ProcedurePrintSelectDialog.cpp \
    src/View/ProcedureDialog/CommonFields/CommonFields.cpp \
    src/View/ProcedureDialog/ProcedureDialog.cpp \
    src/View/ProcedureDialog/ProcedureFields/CrownView.cpp \
    src/View/ProcedureDialog/ProcedureFields/FiberSplintView.cpp \
    src/View/ProcedureDialog/ProcedureFields/ObturationView.cpp \
    src/View/ProcedureDialog/ProcedureModel.cpp \
    src/View/ProcedureDialog/Widgets/CommonFields/CommonFields.cpp \
    src/View/ProcedureDialog/Widgets/CrownView/CrownView.cpp \
    src/View/ProcedureDialog/Widgets/ImplantView/ImplantView.cpp \
    src/View/ProcedureDialog/Widgets/ObturationView/ObturationView.cpp \
    src/View/ProcedureDisplayModel/KSMPModel.cpp \
    src/View/ProcedureDisplayModel/ProcedureSelectModel.cpp \
    src/View/ProcedureDisplayModel/ProcedureTable.cpp \
    src/View/ProcedureDisplayModel/ProcedureTableModel.cpp \
    src/View/ProcedureDisplayModel/ProcedureTemplateModel.cpp \
    src/View/ProcedureDisplayModel/QProcedure.cpp \
    src/View/ProcedureEditDialog/ProcedureEditDialog.cpp \
    src/View/ReportDialog/ReportDialog.cpp \
    src/View/ReportDialog/ReportErrorDialog/ReportErrorDialog.cpp \
    src/View/SaveAsDateDialog/SaveAsDateDialog.cpp \
    src/View/SettingsDialog/GeneralSettings/GeneralSettings.cpp \
    src/View/SettingsDialog/PracticeDoctorSettings/IPracticeDoctorSettings.cpp \
    src/View/SettingsDialog/PracticeDoctorSettings/PracticeDoctorSettings.cpp \
    src/View/SettingsDialog/PracticeSettings/PracticeSettings.cpp \
    src/View/SettingsDialog/PriceListSettings/PriceListSettings.cpp \
    src/View/SettingsDialog/ProcedureTemplateDialog/ProcedureTemplateDialog.cpp \
    src/View/SettingsDialog/SettingsDialog.cpp \
    src/View/TabView/ITabView.cpp \
    src/View/TabView/TabTitle.cpp \
    src/View/TabView/TabView.cpp \
    src/View/Theme.cpp \
    src/View/ToothPaintDevices/SpriteRect.cpp \
    src/View/ToothPaintDevices/SpriteSheets.cpp \
    src/View/ToothPaintDevices/ToothPainter.cpp \
    src/View/Torque.cpp \
    src/View/saveAsDialog/SaveAsDialog.cpp \
    src/View/saveDialog/SaveDialog.cpp \
    src/View/uiComponents/AbstractDateEdit.cpp \
    src/View/uiComponents/AbstractLineEdit.cpp \
    src/View/uiComponents/AbstractUIElement.cpp \
    src/View/uiComponents/qt_derived/CityLineEdit.cpp \
    src/View/uiComponents/qt_derived/ComboBox.cpp \
    src/View/uiComponents/qt_derived/DateEdit.cpp \
    src/View/uiComponents/qt_derived/HalfRoundedButton.cpp \
    src/View/uiComponents/qt_derived/IconButton.cpp \
    src/View/uiComponents/qt_derived/LeadingZeroSpinBox.cpp \
    src/View/uiComponents/qt_derived/LineEdit.cpp \
    src/View/uiComponents/qt_derived/NameEdit.cpp \
    src/View/uiComponents/qt_derived/PixmapLabel.cpp \
    src/View/uiComponents/qt_derived/RangeWidget.cpp \
    src/View/uiComponents/qt_derived/SpinBox.cpp \
    src/View/uiComponents/qt_derived/SurfaceSelector.cpp \
    src/View/uiComponents/qt_derived/TextEdit.cpp \
    src/View/uiComponents/qt_derived/UserButton.cpp \
    src/View/uiComponents/qt_derived/VitaWidget.cpp \
    src/View/uiComponents/qt_derived/Widgets/CrownWidget.cpp \
    src/View/uiComponents/qt_derived/Widgets/DentistMadeWidget.cpp \
    src/View/uiComponents/qt_derived/Widgets/ImplantView.cpp \
    src/View/uiComponents/qt_derived/Widgets/ObturationWidget.cpp \
    src/View/uiComponents/qt_derived/Widgets/PathologyWidget.cpp \
    src/View/uiComponents/qt_derived/Widgets/RangeWidget.cpp \
    src/View/uiComponents/qt_derived/Widgets/SurfaceSelector.cpp \
    src/View/uiComponents/qt_derived/Widgets/TileButton.cpp \
    src/View/uiComponents/qt_derived/Widgets/VitaWidget.cpp \
    src/main.cpp



HEADERS += \
    src/Database/AbstractORM.h \
    src/Database/Database.h \
    src/Database/DbAmbList.h \
    src/Database/DbDoctor.h \
    src/Database/DbInvoice.h \
    src/Database/DbListOpener.h \
    src/Database/DbNotes.h \
    src/Database/DbPatient.h \
    src/Database/DbPatientSummary.h \
    src/Database/DbPerio.h \
    src/Database/DbPractice.h \
    src/Database/DbProcedure.h \
    src/Database/sqLite/sqlite3.h \
    src/Database/sqLite/sqlite3ext.h \
    src/JsonCpp/json-forwards.h \
    src/JsonCpp/json.h \
    src/Model/AmbList.h \
    src/Model/AmbListRow.h \
    src/Model/AmbListValidator.h \
    src/Model/CheckState.h \
    src/Model/CityCode.h \
    src/Model/Date.h \
    src/Model/Financial/BusinessOperation.h \
    src/Model/Financial/FinancialEnums.h \
    src/Model/Financial/Invoice.h \
    src/Model/Financial/Issuer.h \
    src/Model/Financial/MonthNotifRow.h \
    src/Model/Financial/NzokInvoiceData.h \
    src/Model/Financial/Recipient.h \
    src/Model/FreeFunctions.h \
    src/Model/InsuranceStatus.h \
    src/Model/KSMP.h \
    src/Model/Parser/Parser.h \
    src/Model/Patient.h \
    src/Model/PerioStatistic.h \
    src/Model/PerioStatus.h \
    src/Model/PerioToothData.h \
    src/Model/Procedure/CustomProcedures.h \
    src/Model/Procedure/MasterNZOK.h \
    src/Model/Procedure/NZOKmaps.h \
    src/Model/Procedure/PackageCounter.h \
    src/Model/Procedure/Procedure.h \
    src/Model/Procedure/ProcedureApplier.h \
    src/Model/Procedure/ProcedureParser.h \
    src/Model/Procedure/ProcedureTemplate.h \
    src/Model/Procedure/TableStructs.h \
    src/Model/Settings.h \
    src/Model/TableRows.h \
    src/Model/TimeFrame.h \
    src/Model/Tooth/BridgeAlgorithms.h \
    src/Model/Tooth/DiagnosisContainer.h \
    src/Model/Tooth/Enums.h \
    src/Model/Tooth/Status.h \
    src/Model/Tooth/StatusData.h \
    src/Model/Tooth/SurfStatus.h \
    src/Model/Tooth/Tooth.h \
    src/Model/Tooth/ToothContainer.h \
    src/Model/Tooth/ToothController/BridgeController.h \
    src/Model/Tooth/ToothController/GeneralStatusControler.h \
    src/Model/Tooth/ToothController/SurfaceController.h \
    src/Model/Tooth/ToothController/ToothController.h \
    src/Model/Tooth/ToothParser.h \
    src/Model/Tooth/ToothUtils.h \
    src/Model/Tooth/Vita.h \
    src/Model/User/User.h \
    src/Model/User/UserStructs.h \
    src/Model/Validator/AbstractValidator.h \
    src/Model/Validator/BulstatValidator.h \
    src/Model/Validator/CommonValidators.h \
    src/Model/Validator/DateValidator.h \
    src/Model/Validator/LpkValidator.h \
    src/Model/Validator/NameValidator.h \
    src/Model/Validator/NzokContractValidator.h \
    src/Model/Validator/PatientValidators.h \
    src/Model/Validator/ProcedureDateValidator.h \
    src/Model/Validator/ProcedureValidators.h \
    src/Model/Validator/RziValidaor.h \
    src/Model/XML/xml.h \
    src/Network/Base64Convert.h \
    src/Network/Network.h \
    src/Network/PISServ.h \
    src/Network/PKCS11.h \
    src/Network/ReplyHandlers/AbstractReplyHandler.h \
    src/Network/ReplyHandlers/DentalActivitiesHandler.h \
    src/Network/ReplyHandlers/FileSentHandler.h \
    src/Network/ReplyHandlers/HirbnoReplyHandler.h \
    src/Network/ReplyHandlers/MonthNotifDataHandler.h \
    src/Network/ReplyHandlers/NotifListHandler.h \
    src/Network/ReplyHandlers/NraReplyHandler.h \
    src/Network/XmlSigner.h \
    src/Presenter/AddPracticePresenter/AddPracticePresenter.h \
    src/Presenter/AllergiesDialog/AllergiesDialogPresenter.h \
    src/Presenter/AmbListPagePresenter.h \
    src/Presenter/DetailsPresenter/DetailedStatusPresenter.h \
    src/Presenter/DetailsPresenter/DetailsPresenter.h \
    src/Presenter/DetailsPresenter/StatusController.h \
    src/Presenter/DoctorDialogPresenter/DoctorDialogPresenter.h \
    src/Presenter/FinancialPresenter/FinancialPresenter.h \
    src/Presenter/ListPresenter/CheckState.h \
    src/Presenter/ListPresenter/Editor.h \
    src/Presenter/ListPresenter/InputEnums.h \
    src/Presenter/ListPresenter/ListPresenter.h \
    src/Presenter/ListPresenter/ProcedurePresenter/ProcedurePresenter.h \
    src/Presenter/ListPresenter/StatusPresenter/CheckModelCreator.h \
    src/Presenter/ListPresenter/StatusPresenter/InputEnums.h \
    src/Presenter/ListPresenter/StatusPresenter/StatusControl.h \
    src/Presenter/ListPresenter/StatusPresenter/StatusPresenter.h \
    src/Presenter/ListPresenter/StatusPresenter/SurfacePanel/ButtonSurfaceMatrix.h \
    src/Presenter/ListPresenter/StatusPresenter/SurfacePanel/SurfacePanelPresenter.h \
    src/Presenter/ListPresenter/StatusPresenter/ToothHintCreator.h \
    src/Presenter/ListPresenter/SurfacePanel/ButtonSurfaceMatrix.h \
    src/Presenter/ListPresenter/SurfacePanel/SurfacePanelPresenter.h \
    src/Presenter/ListPresenter/ToothHintCreator.h \
    src/Presenter/ListSelector/ListSelectorPresenter.h \
    src/Presenter/LoginPresenter/LoginPresenter.h \
    src/Presenter/MainPresenter.h \
    src/Presenter/MonthNotifLoader.h \
    src/Presenter/PatientDialog/PatientDialogPresenter.h \
    src/Presenter/PatientSummaryPresenter/PatientSummaryPresenter.h \
    src/Presenter/PerioPresenter/PerioPresenter.h \
    src/Presenter/ProcedureDialog/ProcedureDialogPresenter.h \
    src/Presenter/ProcedureDialog/ProcedureEditorPresenter.h \
    src/Presenter/ProcedureDialog/SubPresenters/AbstractSubPresenter.h \
    src/Presenter/ProcedureDialog/SubPresenters/CrownPresenter.h \
    src/Presenter/ProcedureDialog/SubPresenters/EndoPresenter.h \
    src/Presenter/ProcedureDialog/SubPresenters/ExtractionPresenter.h \
    src/Presenter/ProcedureDialog/SubPresenters/FiberSplintPresenter.h \
    src/Presenter/ProcedureDialog/SubPresenters/GeneralMPresenter.h \
    src/Presenter/ProcedureDialog/SubPresenters/GeneralProcedurePresenter.h \
    src/Presenter/ProcedureDialog/SubPresenters/ImplantPresenter.h \
    src/Presenter/ProcedureDialog/SubPresenters/ObturationPresenter.h \
    src/Presenter/ProcedureDialog/SubPresenters/TeethMPresenter.h \
    src/Presenter/ProcedureDialog/SubPresenters/ToothProcedurePresenter.h \
    src/Presenter/ReportDialogPresenter/ReportDialogPresenter.h \
    src/Presenter/SettingsPresenter/PracticeDoctorSettingsPresenter.h \
    src/Presenter/SettingsPresenter/PracticeSettingsPresenter.h \
    src/Presenter/SettingsPresenter/PriceListSettingsPresenter.h \
    src/Presenter/SettingsPresenter/SettingsMainPresenter.h \
    src/Presenter/TabPresenter/ListInstance.h \
    src/Presenter/TabPresenter/TabInstance.h \
    src/Presenter/TabPresenter/TabPresenter.h \
    src/View/AddPracticeDialog/AddPracticeDialog.h \
    src/View/AddPracticeDialog/IAddPracticeDialog.h \
    src/View/AllergiesDialog/AllergiesDialog.h \
    src/View/AllergiesDialog/IAllergiesDialog.h \
    src/View/AmbListPage/AmbListPage.h \
    src/View/AmbListPage/IAmbListPage.h \
    src/View/AmbListPage/TabView/ITabView.h \
    src/View/AmbListPage/TabView/TabBar.h \
    src/View/AmbListPage/TabView/TabView.h \
    src/View/AmbListPage/saveAsDialog/MnogoTypSpinBox.h \
    src/View/AmbListPage/saveAsDialog/SaveAsDialog.h \
    src/View/AmbListPage/saveDialog/SaveDialog.h \
    src/View/AmbListSelector/AmbListSelector.h \
    src/View/AmbListSelector/IListSelectorView.h \
    src/View/AmbListSelector/ListTable.h \
    src/View/AmbListSelector/ListsTableModel.h \
    src/View/AmbListSelector/Models/AmbListTableModel.h \
    src/View/AmbListSelector/Models/FinancialTableModel.h \
    src/View/AmbListSelector/Models/PatientTableModel.h \
    src/View/AmbListSelector/Models/PerioTableModel.h \
    src/View/DetailsView/DetailedStatus.h \
    src/View/DetailsView/DetailsView.h \
    src/View/DetailsView/IDetailedStatusView.h \
    src/View/DetailsView/IDetailsView.h \
    src/View/DoctorSettingsDialog/DoctorSettingsDialog.h \
    src/View/DoctorSettingsDialog/IDoctorSettingsDialog.h \
    src/View/ErrorMessage.h \
    src/View/FinancialView/BusinessOpAddDialog/BusinessOpAddDialog.h \
    src/View/FinancialView/BusinessOpEditDialog/BusinessOpEditDialog.h \
    src/View/FinancialView/BusinessOperationModel.h \
    src/View/FinancialView/FinancialTileButton.h \
    src/View/FinancialView/FinancialView.h \
    src/View/FinancialView/IFinancialView.h \
    src/View/GlobalFunctions.h \
    src/View/IMainView.h \
    src/View/KSMPDialog/KSMPDialog.h \
    src/View/ListView/ControlPanel/ControlPanel.h \
    src/View/ListView/ControlPanel/StatusButton.h \
    src/View/ListView/IListView.h \
    src/View/ListView/IProcedureView.h \
    src/View/ListView/IStatusView.h \
    src/View/ListView/ListView.h \
    src/View/ListView/Procedures/ProcedureTable.h \
    src/View/ListView/Procedures/ProcedureTableModel.h \
    src/View/ListView/Procedures/RowData.h \
    src/View/ListView/SurfacePanel/CPTooth.h \
    src/View/ListView/SurfacePanel/ControlPanelPolygon.h \
    src/View/ListView/SurfacePanel/ISurfacePanel.h \
    src/View/ListView/SurfacePanel/SurfacePanel.h \
    src/View/ListView/TeethView/BridgeItem.h \
    src/View/ListView/TeethView/ContextMenu.h \
    src/View/ListView/TeethView/DsnToothGraphicsItem.h \
    src/View/ListView/TeethView/GraphicsView.h \
    src/View/ListView/TeethView/SelectionBox.h \
    src/View/ListView/TeethView/TeethViewScene.h \
    src/View/ListView/TeethView/ToothGraphicsItem.h \
    src/View/ListView/ToothPaintDevices/BridgePainter.h \
    src/View/ListView/ToothPaintDevices/CPToothPainter.h \
    src/View/ListView/ToothPaintDevices/PaintHint.h \
    src/View/ListView/ToothPaintDevices/SpriteRect.h \
    src/View/ListView/ToothPaintDevices/SpriteSheets.h \
    src/View/ListView/ToothPaintDevices/ToothPainter.h \
    src/View/ListView/ToothPaintDevices/ToothSprite.h \
    src/View/ListView/tilebutton.h \
    src/View/LoginView/ILoginView.h \
    src/View/LoginView/LoginView.h \
    src/View/LoginView/PracticeListDialog.h \
    src/View/ModalDialogBuilder.h \
    src/View/MonthNotifDialog/MonthNotifDialog.h \
    src/View/MonthNotifDialog/MonthNotifTableModel.h \
    src/View/PISHistoryDialog/PISHistoryDialog.h \
    src/View/PatientDialog/IPatientDialog.h \
    src/View/PatientDialog/PatientFormDialog.h \
    src/View/PatientSummaryView/IPatientSummaryView.h \
    src/View/PatientSummaryView/PatientSummary.h \
    src/View/PatientSummaryView/TeethView/TeethBuccalScene.h \
    src/View/PatientSummaryView/TeethView/TeethLingualScene.h \
    src/View/PerioView/IPerioView.h \
    src/View/PerioView/PerioGraphics/HexagonGraphicsItem.h \
    src/View/PerioView/PerioGraphics/PerioChartItem.h \
    src/View/PerioView/PerioGraphics/PerioGraphicsButton.h \
    src/View/PerioView/PerioGraphics/PerioScene.h \
    src/View/PerioView/PerioView.h \
    src/View/PerioView/StatisticTableModel.h \
    src/View/PerioView/ToothUi.h \
    src/View/PerioView/Widgets/FurcationWidget.h \
    src/View/PerioView/Widgets/PerioButton.h \
    src/View/PerioView/Widgets/PerioSpinBox.h \
    src/View/PerioView/Widgets/PerioStateButton.h \
    src/View/PerioView/Widgets/PerioStatusView.h \
    src/View/PerioView/Widgets/PerioTable.h \
    src/View/PerioView/Widgets/ToothButton.h \
    src/View/PinPromptDialog/PinPromptDialog.h \
    src/View/Printer/Printer.h \
    src/View/Printer/ProcedurePrintSelectDialog.h \
    src/View/ProcedureDialog/CommonFields/CommonFields.h \
    src/View/ProcedureDialog/CommonFields/ICommonFields.h \
    src/View/ProcedureDialog/IProcedureDialog.h \
    src/View/ProcedureDialog/ProcedureDialog.h \
    src/View/ProcedureDialog/ProcedureFields/CrownView.h \
    src/View/ProcedureDialog/ProcedureFields/FiberSplintView.h \
    src/View/ProcedureDialog/ProcedureFields/ICrownView.h \
    src/View/ProcedureDialog/ProcedureFields/IFiberSplintView.h \
    src/View/ProcedureDialog/ProcedureFields/IObturationView.h \
    src/View/ProcedureDialog/ProcedureFields/ObturationView.h \
    src/View/ProcedureDialog/ProcedureModel.h \
    src/View/ProcedureDialog/Widgets/CommonFields/CommonFields.h \
    src/View/ProcedureDialog/Widgets/CommonFields/ICommonFields.h \
    src/View/ProcedureDialog/Widgets/CrownView/CrownView.h \
    src/View/ProcedureDialog/Widgets/CrownView/ICrownView.h \
    src/View/ProcedureDialog/Widgets/ImplantView/IImplantView.h \
    src/View/ProcedureDialog/Widgets/ImplantView/ImplantView.h \
    src/View/ProcedureDialog/Widgets/ObturationView/IObturationView.h \
    src/View/ProcedureDialog/Widgets/ObturationView/ObturationView.h \
    src/View/ProcedureDisplayModel/KSMPModel.h \
    src/View/ProcedureDisplayModel/ProcedureSelectModel.h \
    src/View/ProcedureDisplayModel/ProcedureTable.h \
    src/View/ProcedureDisplayModel/ProcedureTableModel.h \
    src/View/ProcedureDisplayModel/ProcedureTemplateModel.h \
    src/View/ProcedureDisplayModel/QProcedure.h \
    src/View/ProcedureEditDialog/IProcedureEditDialog.h \
    src/View/ProcedureEditDialog/ProcedureEditDialog.h \
    src/View/ReportDialog/IReportDialog.h \
    src/View/ReportDialog/ReportDialog.h \
    src/View/ReportDialog/ReportDialogResult.h \
    src/View/ReportDialog/ReportErrorDialog/ReportErrorDialog.h \
    src/View/SaveAsDateDialog/SaveAsDateDialog.h \
    src/View/SettingsDialog/GeneralSettings/GeneralSettings.h \
    src/View/SettingsDialog/ISettingsDialog.h \
    src/View/SettingsDialog/PracticeDoctorSettings/IPracticeDoctorSettings.h \
    src/View/SettingsDialog/PracticeDoctorSettings/PracticeDoctorSettings.h \
    src/View/SettingsDialog/PracticeSettings/IPacticeSettings.h \
    src/View/SettingsDialog/PracticeSettings/PracticeSettings.h \
    src/View/SettingsDialog/PriceListSettings/IPriceListSettings.h \
    src/View/SettingsDialog/PriceListSettings/PriceListSettings.h \
    src/View/SettingsDialog/ProcedureTemplateDialog/ProcedureTemplateDialog.h \
    src/View/SettingsDialog/SettingsDialog.h \
    src/View/TabView/ITabView.h \
    src/View/TabView/TabTitle.h \
    src/View/TabView/TabView.h \
    src/View/Theme.h \
    src/View/ToothPaintDevices/PaintHint.h \
    src/View/ToothPaintDevices/SpriteRect.h \
    src/View/ToothPaintDevices/SpriteSheets.h \
    src/View/ToothPaintDevices/ToothPainter.h \
    src/View/ToothPaintDevices/ToothSprite.h \
    src/View/Torque.h \
    src/View/saveAsDialog/SaveAsDialog.h \
    src/View/saveDialog/SaveDialog.h \
    src/View/uiComponents/AbstractComboBox.h \
    src/View/uiComponents/AbstractDateEdit.h \
    src/View/uiComponents/AbstractLabel.h \
    src/View/uiComponents/AbstractLineEdit.h \
    src/View/uiComponents/AbstractRangeEdit.h \
    src/View/uiComponents/AbstractSpinBox.h \
    src/View/uiComponents/AbstractSurfaceSelector.h \
    src/View/uiComponents/AbstractUIElement.h \
    src/View/uiComponents/qt_derived/CityLineEdit.h \
    src/View/uiComponents/qt_derived/ComboBox.h \
    src/View/uiComponents/qt_derived/DateEdit.h \
    src/View/uiComponents/qt_derived/HalfRoundedButton.h \
    src/View/uiComponents/qt_derived/IconButton.h \
    src/View/uiComponents/qt_derived/LeadingZeroSpinBox.h \
    src/View/uiComponents/qt_derived/LineEdit.h \
    src/View/uiComponents/qt_derived/NameEdit.h \
    src/View/uiComponents/qt_derived/PixmapLabel.h \
    src/View/uiComponents/qt_derived/RangeWidget.h \
    src/View/uiComponents/qt_derived/SpinBox.h \
    src/View/uiComponents/qt_derived/SurfaceSelector.h \
    src/View/uiComponents/qt_derived/TextEdit.h \
    src/View/uiComponents/qt_derived/UserButton.h \
    src/View/uiComponents/qt_derived/VitaWidget.h \
    src/View/uiComponents/qt_derived/Widgets/AbstractRangeEdit.h \
    src/View/uiComponents/qt_derived/Widgets/CrownWidget.h \
    src/View/uiComponents/qt_derived/Widgets/DentistMadeWidget.h \
    src/View/uiComponents/qt_derived/Widgets/IImplantView.h \
    src/View/uiComponents/qt_derived/Widgets/ImplantView.h \
    src/View/uiComponents/qt_derived/Widgets/ObturationWidget.h \
    src/View/uiComponents/qt_derived/Widgets/PathologyWidget.h \
    src/View/uiComponents/qt_derived/Widgets/RangeWidget.h \
    src/View/uiComponents/qt_derived/Widgets/SurfaceSelector.h \
    src/View/uiComponents/qt_derived/Widgets/TileButton.h \
    src/View/uiComponents/qt_derived/Widgets/VitaWidget.h



FORMS += \
    src/View/AddPracticeDialog/AddPracticeDialog.ui \
    src/View/AllergiesDialog/AllergiesDialog.ui \
    src/View/AmbListPage/AmbListPage.ui \
    src/View/AmbListPage/TabView/TabView.ui \
    src/View/AmbListPage/saveAsDialog/SaveAsDialog.ui \
    src/View/AmbListSelector/AmbListSelector.ui \
    src/View/DetailsView/DetailedStatus.ui \
    src/View/DetailsView/DetailsView.ui \
    src/View/DoctorSettingsDialog/DoctorSettingsDialog.ui \
    src/View/FinancialView/BusinessOpAddDialog/BusinessOpAddDialog.ui \
    src/View/FinancialView/BusinessOpEditDialog/BusinessOpEditDialog.ui \
    src/View/FinancialView/FinancialView.ui \
    src/View/KSMPDialog/KSMPDialog.ui \
    src/View/ListView/ControlPanel/ControlPanel.ui \
    src/View/ListView/ListView.ui \
    src/View/ListView/SurfacePanel/SurfacePanel.ui \
    src/View/LoginView/LoginView.ui \
    src/View/LoginView/PracticeListDialog.ui \
    src/View/MonthNotifDialog/MonthNotifDialog.ui \
    src/View/PISHistoryDialog/PISHistoryDialog.ui \
    src/View/PatientDialog/PatientFormDialog.ui \
    src/View/PatientSummaryView/PatientSummary.ui \
    src/View/PerioView/PerioView.ui \
    src/View/PerioView/Widgets/PerioStatusView.ui \
    src/View/PinPromptDialog/PinPromptDialog.ui \
    src/View/Printer/ProcedurePrintSelectDialog.ui \
    src/View/ProcedureDialog/CommonFields/CommonFields.ui \
    src/View/ProcedureDialog/ProcedureDialog.ui \
    src/View/ProcedureDialog/ProcedureFields/CrownView.ui \
    src/View/ProcedureDialog/ProcedureFields/FiberSplintView.ui \
    src/View/ProcedureDialog/ProcedureFields/ObturationView.ui \
    src/View/ProcedureDialog/Widgets/CommonFields/CommonFields.ui \
    src/View/ProcedureDialog/Widgets/CrownView/CrownView.ui \
    src/View/ProcedureDialog/Widgets/ImplantView/ImplantView.ui \
    src/View/ProcedureDialog/Widgets/ObturationView/ObturationView.ui \
    src/View/ProcedureEditDialog/ProcedureEditDialog.ui \
    src/View/ReportDialog/ReportDialog.ui \
    src/View/ReportDialog/ReportErrorDialog/ReportErrorDialog.ui \
    src/View/SaveAsDateDialog/SaveAsDateDialog.ui \
    src/View/SettingsDialog/GeneralSettings/GeneralSettings.ui \
    src/View/SettingsDialog/PracticeDoctorSettings/PracticeDoctorSettings.ui \
    src/View/SettingsDialog/PracticeSettings/PracticeSettings.ui \
    src/View/SettingsDialog/PriceListSettings/PriceListSettings.ui \
    src/View/SettingsDialog/ProcedureTemplateDialog/ProcedureTemplateDialog.ui \
    src/View/SettingsDialog/SettingsDialog.ui \
    src/View/TabView/TabTitle.ui \
    src/View/TabView/TabView.ui \
    src/View/Torque.ui \
    src/View/saveAsDialog/SaveAsDialog.ui \
    src/View/uiComponents/qt_derived/RangeWidget.ui \
    src/View/uiComponents/qt_derived/SurfaceSelector.ui \
    src/View/uiComponents/qt_derived/VitaWidget.ui \
    src/View/uiComponents/qt_derived/Widgets/CrownWidget.ui \
    src/View/uiComponents/qt_derived/Widgets/DentistMadeWidget.ui \
    src/View/uiComponents/qt_derived/Widgets/ImplantView.ui \
    src/View/uiComponents/qt_derived/Widgets/ObturationWidget.ui \
    src/View/uiComponents/qt_derived/Widgets/PathologyWidget.ui \
    src/View/uiComponents/qt_derived/Widgets/RangeWidget.ui \
    src/View/uiComponents/qt_derived/Widgets/SurfaceSelector.ui \
    src/View/uiComponents/qt_derived/Widgets/VitaWidget.ui


RESOURCES += $$SRC_PATH/View/Torque.qrc \
    src/View/Torque.qrc \
    src/View/Torque.qrc


# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target
