#include "EDental.h"

#include <array>
#include <map>

#include "Model/User.h"
#include <TinyXML/tinyxml.h>
#include "View/ModalDialogBuilder.h"
#include "Model/Dental/ToothContainer.h"

#define sendAutoGeneratedExam

bool EDental::Open::sendRequest(
    const AmbList& ambSheet, 
    const Patient& patient, 
	decltype(m_callback) nrnCallback
)
{
	m_callback = nrnCallback;

	std::string contents;

	bool isNhif = ambSheet.isNhifSheet();

	bool adverseConditions = isNhif && ambSheet.nhifData.isUnfavourable;

	contents.reserve(4000);

	contents +=
		"<nhis:dentalTreatment>"
			+ bind("lrn", ambSheet.lrn)
			//+ bind("basedOn", ambSheet.basedOn) //needs closing functionality
			+ bind("treatmentStart", ambSheet.date)
			//+ bind("treatmentEnd", ambSheet.time.to8601(ambSheet.getDate())) //TO IMPLEMENT!!!
			+ bind("adverseConditions", adverseConditions)
			+ bind("rhifAreaNumber", patient.city.getRhif() + patient.city.getHealthRegion())
			+ "<nhis:medicalStatus />" //TO IMPLEMENT!!!
			+ getProcedures(ambSheet.procedures, ambSheet.teeth, ambSheet.date)
		+"</nhis:dentalTreatment>"
		+ HisService::subject(patient)
		+ HisService::performer()
	;		

	return HisService::sendRequestToHis(contents);
}

std::string EDental::Open::getProcedures(const ProcedureContainer& procedures, const ToothContainer& teeth, const Date& treatmentStartDate)
{

	std::string result;

	result.reserve(1000);

	ToothContainer teethChanged = teeth;

#ifdef sendAutoGeneratedExam
	result += HisService::initialStatusAsProcedure(teeth, treatmentStartDate);
	int sequence = 1;
#else
	int sequence = 0;
#endif

	for (auto& p : procedures)
	{
		sequence++;
		result += HisService::getProcedure(p, teeth, teethChanged, sequence);
	}

	return result;

}

void EDental::Open::parseReply(const std::string& reply)
{
	auto errors = getErrors(reply);

	if (errors.size()) {
		
		if (FreeFn::contains(errors, "Вече има подаден")) {
			auto existingNrn = errors.substr(errors.size() - 12);
			m_callback(existingNrn, {}, true);
			return;
		}

		ModalDialogBuilder::showError(errors);
		m_callback = nullptr;
		return;


	}

	TiXmlDocument doc;

	doc.Parse(reply.data(), 0, TIXML_ENCODING_UTF8);

	TiXmlHandle docHandle(&doc);

	auto nrn = docHandle.
		FirstChild(). //message
		Child(1).	  //contents
		FirstChildElement().ToElement(); //nrn

	std::string nrnStr;

	if (nrn) {
		nrnStr = nrn->Attribute("value");
	}

	std::vector<int> procedureIndex;

	auto contents = docHandle.
		FirstChild(). //message
		Child(1);	  //contents


	//dentalProcedures
	for (int i = 3; contents.Child(i).ToElement(); i++)
	{
		auto index = std::stoi(contents.Child(i).Child(1).ToElement()->Attribute("value"));
		auto sequence = std::stoi(contents.Child(i).Child(0).ToElement()->Attribute("value"));

#ifdef sendAutoGeneratedExam
		if (sequence == 1) continue; //the first procedure is always the initial status
#endif
		//index
		procedureIndex.push_back(index);
	}

	m_callback(nrnStr, procedureIndex, false);

}


bool EDental::Augment::sendRequest(const AmbList& ambSheet, const Patient& patient, std::function<void(const std::map<int, int>& procedureIndexes)> callback)
{
	m_callback = callback;

	std::string contents;

	bool isNhif = ambSheet.isNhifSheet();

	bool adverseConditions = isNhif && ambSheet.nhifData.isUnfavourable;

	contents.reserve(4000);

	std::string resultingDocuments = "<nhis:documents>";

	for(auto& ref : ambSheet.referrals) resultingDocuments += bind("nrnReferral", ref.nrn);

	//implement prescriptions and medical notices here

	resultingDocuments += "</nhis:documents>";

	contents +=
		"<nhis:dentalTreatment>"
		+ bind("nrnDental", ambSheet.nrn)
		//+ bind("basedOn", ambSheet.basedOn)
		+ bind("treatmentStart", ambSheet.date)
		+ bind("adverseConditions", adverseConditions)
		+ bind("rhifAreaNumber", patient.city.getRhif() + patient.city.getHealthRegion())
		+ "<nhis:medicalStatus />" //TO IMPLEMENT!!!
		+ resultingDocuments
		+ getProcedures(ambSheet.procedures, ambSheet.teeth, ambSheet.date)
		+ "</nhis:dentalTreatment>"
		+ HisService::subject(patient)
		+ HisService::performer()
		;

	return HisService::sendRequestToHis(contents);
}

std::string EDental::Augment::getProcedures(const ProcedureContainer& procedures, const ToothContainer& teeth, const Date& treatmentStartDate)
{
	
	std::string result;

	result.reserve(1000);

#ifdef sendAutoGeneratedExam
	result += HisService::initialStatusAsProcedure(teeth, treatmentStartDate);
	int sequence = 1;
#else
	int sequence = 0;
#endif

	ToothContainer teethChanged = teeth;

	for (auto& p : procedures)
	{
		sequence++;

		result += HisService::getProcedure(p, teeth, teethChanged, sequence);

	}

	sequence = 999;

	for (auto& p : procedures.removedProcedures()) {

		sequence++;

		result += "<nhis:dentalProcedure>";

		result += bind("sequence", sequence);

		result += bind("index", p.his_index);

		result += bind("code", p.code.code());

		result += bind("status", 7);

		result += bind("type", p.code.hisType());

		result += bind("datePerformed", p.date.to8601());

		result += bind("financingSource", static_cast<int>(p.financingSource));

		result += "</nhis:dentalProcedure>";

	}
	
	return result;
	
}

void EDental::Augment::parseReply(const std::string& reply)
{
	auto errors = getErrors(reply);

	if (errors.size()) {
		ModalDialogBuilder::showError(errors);
		m_callback = nullptr;
		return;
	}

	TiXmlDocument doc;

	doc.Parse(reply.data(), 0, TIXML_ENCODING_UTF8);

	TiXmlHandle docHandle(&doc);

	auto contents = docHandle.
		FirstChild(). //message
		Child(1);	  //contents

	std::map<int, int> procedureIndex;

	//dentalProcedures
	for (int i = 2; contents.Child(i).ToElement(); i++)
	{
		//sequence
		auto sequence = std::stoi(contents.Child(i).Child(0).ToElement()->Attribute("value"));
		//index
		auto hisIdx = std::stoi(contents.Child(i).Child(1).ToElement()->Attribute("value"));

#ifdef sendAutoGeneratedExam
		if (sequence == 1) continue; //the first procedure is always the initial status
#endif
		
		if (sequence >= 999) continue;

		procedureIndex[sequence-2] = hisIdx;
	}

	m_callback(procedureIndex);
}

bool EDental::Cancel::sendRequest(const std::string& nrn, std::function<void(bool)> success)
{
	m_callback = success;

	auto reason = ModalDialogBuilder::inputDialog(
		"Основание за анулиране на денталния преглед:",
		"Анулиране на дентален преглед"
	);

	if (reason.empty()) return false;

	std::string contents =
		bind("nrnDental", nrn)
		+ bind("cancelReason", reason);

	return HisService::sendRequestToHis(contents);
}

void EDental::Cancel::parseReply(const std::string& reply)
{
	auto errors = getErrors(reply);

	if (errors.size()) {
		ModalDialogBuilder::showError(errors);
		m_callback = nullptr;
		return;
	}

	TiXmlDocument doc;

	doc.Parse(reply.data(), 0, TIXML_ENCODING_UTF8);

	TiXmlHandle docHandle(&doc);

	auto status = docHandle.
		FirstChild(). //message
		Child(1).	  //contents
		Child(1).ToElement(); //status

	if (
		status &&
		status->FirstAttribute()->IntValue() == 3
		)
	{
		m_callback(true); return;
	}

	m_callback(false);

}


bool EDental::GetStatus::sendRequest(const Patient& patient, std::function<void(const ToothContainer&)> callback)
{
	m_callback = callback;

	std::string contents =
		bind("identifierType", patient.type) +
		bind("identifier", patient.id) +
		bind("fromDate", Date::currentDate().to8601()) +
		bind("toDate", Date::currentDate().to8601()) +
		bind("practiceNumber", User::practice().rziCode)
		;

	return HisService::sendRequestToHis(contents);
}

void EDental::GetStatus::parseReply(const std::string& reply)
{
	auto errors = getErrors(reply);

	if (errors.size()) {
		ModalDialogBuilder::showError(errors);
		m_callback = nullptr;
		return;
	}

	//ModalDialogBuilder::showMultilineDialog(reply);

	TiXmlDocument doc;

	doc.Parse(reply.data(), 0, TIXML_ENCODING_UTF8);

	TiXmlHandle docHandle(&doc);

	auto contents = docHandle.
		FirstChild(). //message
		Child(1);	  //contents


	//getting most recent status

	ToothContainer teeth;

	struct Ranges {
		std::vector<int> splints;
		std::vector<int> bridges;
		std::vector<int> pontics;
	};

	Ranges ranges;

	static std::map<std::string, std::function<void(Tooth& tooth, Ranges& r)>> lambdaMap
	{
		{"E",	[](Tooth& tooth, Ranges& r) mutable { tooth.extraction.set(true); }},
		{"T",	[](Tooth& tooth, Ranges& r) mutable { tooth.calculus.set(true); }},
		{"K",	[](Tooth& tooth, Ranges& r) mutable { tooth.crown.set(true); }},
		{"B",	[](Tooth& tooth, Ranges& r) mutable { r.bridges.push_back(tooth.index); r.pontics.push_back(tooth.index); }},
		{"Kb",	[](Tooth& tooth, Ranges& r) mutable { r.bridges.push_back(tooth.index); }},
		{"O",	[](Tooth& tooth, Ranges& r) mutable { tooth.obturation.set(true); }},
		{"C",	[](Tooth& tooth, Ranges& r) mutable { tooth.caries.set(true); }},
		{"Oo",	[](Tooth& tooth, Ranges& r) mutable { tooth.obturation.set(true, Surface::Occlusal); }},
		{"Om",	[](Tooth& tooth, Ranges& r) mutable { tooth.obturation.set(true, Surface::Medial);  }},
		{"Od",	[](Tooth& tooth, Ranges& r) mutable { tooth.obturation.set(true, Surface::Distal);  }},
		{"Ob",	[](Tooth& tooth, Ranges& r) mutable { tooth.obturation.set(true, Surface::Buccal); }},
		{"Ol",	[](Tooth& tooth, Ranges& r) mutable { tooth.obturation.set(true, Surface::Lingual);  }},
		{"Oc",	[](Tooth& tooth, Ranges& r) mutable { tooth.obturation.set(true, Surface::Cervical);  }},
		{"Co",	[](Tooth& tooth, Ranges& r) mutable { tooth.caries.set(true, Surface::Occlusal); }},
		{"Cm",	[](Tooth& tooth, Ranges& r) mutable { tooth.caries.set(true, Surface::Medial);  }},
		{"Cd",	[](Tooth& tooth, Ranges& r) mutable { tooth.caries.set(true, Surface::Distal);  }},
		{"Cb",	[](Tooth& tooth, Ranges& r) mutable { tooth.caries.set(true, Surface::Buccal); }},
		{"Cl",	[](Tooth& tooth, Ranges& r) mutable { tooth.caries.set(true, Surface::Lingual);  }},
		{"Cc",	[](Tooth& tooth, Ranges& r) mutable { tooth.caries.set(true, Surface::Cervical);  }},
		{"M1",	[](Tooth& tooth, Ranges& r) mutable { tooth.mobility.set(true); tooth.mobility.degree = Degree::First; }},
		{"M2",	[](Tooth& tooth, Ranges& r) mutable { tooth.mobility.set(true); tooth.mobility.degree = Degree::Second; }},
		{"M3",	[](Tooth& tooth, Ranges& r) mutable { tooth.mobility.set(true); tooth.mobility.degree = Degree::Third; }},
		{"X",	[](Tooth& tooth, Ranges& r) mutable { tooth.denture.set(true); }},
		{"R",	[](Tooth& tooth, Ranges& r) mutable { tooth.root.set(true); }},
		{"Rc",	[](Tooth& tooth, Ranges& r) mutable { tooth.endo.set(true); }},
		{"Rp",	[](Tooth& tooth, Ranges& r) mutable { tooth.post.set(true); }},
		{"H",	[](Tooth& tooth, Ranges& r) mutable { tooth.healthy.set(true); }},
		{"I",	[](Tooth& tooth, Ranges& r) mutable { tooth.implant.set(true); }},
		{"Re",	[](Tooth& tooth, Ranges& r) mutable { tooth.impacted.set(true); }},
		{"G",	[](Tooth& tooth, Ranges& r) mutable { tooth.lesion.set(true); }},
		{"P",	[](Tooth& tooth, Ranges& r) mutable { tooth.pulpitis.set(true); }},
		{"F",	[](Tooth& tooth, Ranges& r) mutable { tooth.fracture.set(true); }},
		{"Pa",	[](Tooth& tooth, Ranges& r) mutable { tooth.periodontitis.set(true); }},
		{"D",	[](Tooth& tooth, Ranges& r) mutable { tooth.dsn.set(true); }},
		{"S",	[](Tooth& tooth, Ranges& r) mutable { r.splints.push_back(tooth.index); }}
	};


	auto status = contents.Child(0);

	//parsing the status
	for (int i = 0; status.Child(i).ToElement() != nullptr; i++) //tooth
	{

		auto [index, temp, dsn] = ToothUtils::getToothFromNhifNum(status.Child(i).Child(0).ToElement()->Attribute("value")); //toothIndex

		teeth[index].temporary.set(temp);
		
		for (int y = 2; status.Child(i).Child(y).ToElement() != nullptr; y++) 
		{
			auto condition = status.Child(i).Child(y).ToElement();

			if (condition->ValueStr() == "nhis:supernumeralIndex")  //supernumeralIndex
			{
				teeth[index].setStatus(StatusCode::Dsn, true);
				teeth[index].dsn.tooth().setStatus(StatusCode::Healthy, true); //only temporary, until NHIS starts returning the supernumeral tooth status 
				dsn = true;
				continue;
			}
			
			auto code = condition->FirstChildElement()->Attribute("value"); //condition

			auto& tooth = dsn ? teeth[index].dsn.tooth() : teeth[index];

			if (lambdaMap.count(code))
			{
				lambdaMap[code](tooth, ranges);
			}
		}

	}

	teeth.setStatus(ranges.splints, StatusType::general, StatusCode::FiberSplint, true);
	teeth.setStatus(ranges.bridges, StatusType::general, StatusCode::Bridge, true);

	//in case extraction is not set on pontics:
	for (auto idx : ranges.pontics) if (teeth[idx].canHaveACrown()) teeth[idx].extraction.set(false);
	

	m_callback(teeth);

	m_callback = nullptr;

}

void EDental::GetProcedures::parseReply(const std::string& reply)
{
	if (reply.empty()) {
		m_callback({});
		return;
	}

	auto errors = getErrors(reply);

	if (errors.size()) {
		if (show_dialogs) {
			ModalDialogBuilder::showError(errors);
		}
		m_callback = nullptr;
		return;
	}

	TiXmlDocument doc;

	doc.Parse(reply.data(), 0, TIXML_ENCODING_UTF8);

	TiXmlHandle docHandle(&doc);

	auto contents = docHandle.
		FirstChild(). //message
		Child(1);	  //contents
	//parsing procedures
	std::vector<Procedure> procedures;

	std::vector<ToothIndex> teethIndexes;

	for (int i = 1; contents.Child(i).ToElement() != nullptr; i++)
	{
		auto pXml = contents.Child(i);


		procedures.emplace_back();

		auto& p = procedures.back();

		p.date = Date(pXml.Child(5).ToElement()->Attribute("value"));
		p.code = ProcedureCode(pXml.Child(2).ToElement()->Attribute("value"));
		p.financingSource = static_cast<FinancingSource>(std::stoi(pXml.Child(6).ToElement()->Attribute("value")));
		p.db_source = Procedure::DatabaseSource::HIS;

		int y = 7;

		while (true)
		{

			if (pXml.Child(y).ToElement() == nullptr) break;

			auto elementName = pXml.Child(y).ToElement()->ValueStr();

			//parsing teeth indexes:
			if (elementName == "nhis:tooth" && p.code.type() != ProcedureType::full_exam)
			{
				auto index = ToothUtils::getToothFromNhifNum(pXml.Child(y).Child(0).ToElement()->Attribute("value"));

				index.supernumeral = pXml.Child(y).Child(1).ToElement()->ValueStr() == "nhis:supernumeralIndex";

				teethIndexes.push_back(index);

			}

			//parsing notes
			if (elementName == "nhis:note")
			{
				p.notes = pXml.Child(y).ToElement()->Attribute("value");
			}
			
	

			//parsing diagnosis
			if (elementName == "nhis:diagnosis")
			{
				auto diagHandle = pXml.Child(y);
				p.diagnosis = std::stoi(diagHandle.Child(0).ToElement()->Attribute("value"));

				if (diagHandle.Child(1).ToElement() != nullptr)
				{
					p.diagnosis.description = diagHandle.Child(1).ToElement()->Attribute("value");
				}


			}

			y++;
		}

		if (std::string(pXml.Child(3).ToElement()->Attribute("value")) == "7") {

			p.notes = "АНУЛИРАНА";
		}

		//separating procedures according to teeth affected
		for (int j = 0; j < teethIndexes.size(); j++)
		{
			if (j != 0) { procedures.push_back(procedures.back()); };

			auto& idx = teethIndexes[j];

			procedures.back().tooth_idx = idx;

		}

		teethIndexes.clear();
	}

	m_callback(procedures);

	m_callback = nullptr;

}

bool EDental::GetProcedures::sendRequest(const Patient& patient, bool showDialogs, decltype(m_callback) callback)
{

	this->show_dialogs = showDialogs;

	m_callback = callback;

	std::string contents =
		bind("identifierType", patient.type) +
		bind("identifier", patient.id) +
		bind("fromDate", "2023-05-01") +
		bind("toDate", Date::currentDate().to8601()) +
		bind("practiceNumber", User::practice().rziCode)
		;

	return HisService::sendRequestToHis(contents);
}
